#!/usr/bin/env python3
import os
import sys
import base64
import hashlib


def generate_password_hash(pw: bytes) -> bytes:
    salt = os.urandom(32)
    hashed = hashlib.pbkdf2_hmac(
        hash_name='sha256',
        password=pw,
        salt=salt,
        iterations=100_000,
    )
    return salt + hashed


def format_hash(hashed: bytes) -> str:
    return base64.b64encode(hashed).decode()


if __name__ == '__main__':
    print(
        format_hash(
            generate_password_hash(sys.argv[1].encode())
        )
    )
